server:
  port: 9092
  servlet:
    context-path: /notification-management

spring:
  application:
    name: NOTIFICATION-MANAGEMENT
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_notification-management
    username: freedb_online_cm
    password: qV?x$decE4m??VS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: onlinelearningtest819@gmail.com
    password: prsnhkbtqmkkbqsf
    properties:
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      smtp.writetimeout: 5000
      mail.smtp.starttls.enable: true
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka